// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJATh8havl2C0658fBtLppcQoy0Xlz0aM',
    appId: '1:681893406474:web:f7003f3833fa2585957cf3',
    messagingSenderId: '681893406474',
    projectId: 'pvp-traders-app-5ed1e',
    authDomain: 'pvp-traders-app-5ed1e.firebaseapp.com',
    storageBucket: 'pvp-traders-app-5ed1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw8dycJPjWQt6UqC5rFIhRys-84Rv_9-U',
    appId: '1:681893406474:android:9808a0b40ac9ee83957cf3',
    messagingSenderId: '681893406474',
    projectId: 'pvp-traders-app-5ed1e',
    storageBucket: 'pvp-traders-app-5ed1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq6--yPAyanGc09Dbnx6IZ2wuce_cqeg',
    appId: '1:681893406474:ios:7471a5373dced522957cf3',
    messagingSenderId: '681893406474',
    projectId: 'pvp-traders-app-5ed1e',
    storageBucket: 'pvp-traders-app-5ed1e.firebasestorage.app',
    iosBundleId: 'com.pvptraders.pvpTraders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq6--yPAyanGc09Dbnx6IZ2wuce_cqeg',
    appId: '1:681893406474:ios:7471a5373dced522957cf3',
    messagingSenderId: '681893406474',
    projectId: 'pvp-traders-app-5ed1e',
    storageBucket: 'pvp-traders-app-5ed1e.firebasestorage.app',
    iosBundleId: 'com.pvptraders.pvpTraders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJATh8havl2C0658fBtLppcQoy0Xlz0aM',
    appId: '1:681893406474:web:78ca59a449f5abb6957cf3',
    messagingSenderId: '681893406474',
    projectId: 'pvp-traders-app-5ed1e',
    authDomain: 'pvp-traders-app-5ed1e.firebaseapp.com',
    storageBucket: 'pvp-traders-app-5ed1e.firebasestorage.app',
  );
}
